# Generated by Django 5.2.7 on 2025-11-05 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0003_alter_journal_visibility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='visibility',
            field=models.CharField(choices=[('PUBLIC', 'Public'), ('PRIVATE', 'Private'), ('SPECIFIC', 'Specific'), ('FRIENDS', 'Friends')], default='PUBLIC', max_length=10),
        ),
    ]
